### ISSUE TITLE
App Crash after Changing Settings to allow Photo Access 

### ISSUE THREAD

**Issue by justinlevi** [AlexLittlejohn/ALCameraViewController#10]
Tested on the simulator only. If you deny access to the photo album, click the deep link button to change the setting, grant access, the app crashes. Is this expected behavior?

**Comment by AlexLittlejohn** [comment]
This is the expected behaviour as defined by iOS. When changing permissions this way it will restart the app in order for the permissions to take effect.

**Comment by wintercreative** [comment]
Ahh, thanks for the explanation.
