### ISSUE TITLE
Allow defaulting to front camera

### ISSUE THREAD

**Issue by simoami** [AlexLittlejohn/ALCameraViewController#107]
In an a profile image view, it makes sense for the camera view to default to `UIImagePickerControllerCameraDevice.Front`. It would help to add this tiny but helpful setting.

**Comment by yigitserin** [comment]
I also would like to allow gallery to be the default selection.

**Comment by AlexLittlejohn** [comment]
Added in 1.2.3

**Comment by harolhiguera** [comment]
Hi AlexLittlejohn,

Sorry for reopening this issue, would it be possible for you to tell me how to make the front camera the default one, please?

Thank you, and thank you for this great project.
