### ISSUE TITLE
support for old swift version

### ISSUE THREAD

**Issue by satyamub** [AlexLittlejohn/ALCameraViewController#108]
can you add old swift code supported version here ? I have not updated yet to new swift. and I typically need this.

**Comment by AlexLittlejohn** [comment]
This is not possible. You can download an older release which supports the swift version you require.

**Comment by satyamub** [comment]
can you please let me know the place to download?

**Comment by AlexLittlejohn** [comment]
https://github.com/AlexLittlejohn/ALCameraViewController/releases
