### ISSUE TITLE
ALCameraViewController wont dismiss after press confirm or press cancel

### ISSUE THREAD

**Issue by Tj3n** [AlexLittlejohn/ALCameraViewController#110]
Hi, as the title, im having this issue where the viewcontroller just doesnt want to dismiss it self after press confirm or cancel, but still called into the closure, how should i fix it?

**Comment by AlexLittlejohn** [comment]
Inside your completion closure just call `self.dismissViewController` method

**Comment by Tj3n** [comment]
thanks
