### ISSUE TITLE
Not working with Version 7.2.1 (7C1002)

### ISSUE THREAD

**Issue by vimalprakashts** [AlexLittlejohn/ALCameraViewController#116]
Breaks in #selector()

**Comment by AlexLittlejohn** [comment]
The project requires swift 2.2 in order to compile. You will have to update your Xcode to the latest if you want to use it.

**Comment by vimalprakashts** [comment]
@AlexLittlejohn  thank you for the quick response

**Comment by vimalprakashts** [comment]
after update works now. thank you

**Comment by AlexLittlejohn** [comment]
Cool beans :)
