### ISSUE TITLE
Question: How to start

### ISSUE THREAD

**Issue by devJoshLopez** [AlexLittlejohn/ALCameraViewController#118]
Hello, I am new to xcode and swift. i was able to get this with cocoapods and figured out I had to import this in the top of my viewcontroller but when I put in the code in the readme I get an error that says "Value of type 'RegisterViewController?' has no member 'dismissViewController'"

my code looks like: 
@IBAction func profileImageButtonTouched(sender: AnyObject) {
        let croppingEnabled = true
        let cameraViewController = CameraViewController(croppingEnabled: croppingEnabled) { [weak self] image, asset in
            // Do something with your image here.
            // If cropping is enabled this image will be the cropped version
            self.dismissViewController(animated: true, completion: nil)
        }
        presentViewController(cameraViewController, animated: true, completion: nil)
    }

**Comment by AlexLittlejohn** [comment]
the problem is with this line -> `self.dismissViewController(animated: true, completion: nil)`.
It should be `self?.dismissViewControllerAnimated(true, completion: nil)`. This is a mistake in the readme which I will fix shortly.
