### ISSUE TITLE
Allow selecting squares bigger than the original picture (with black fill)

### ISSUE THREAD

**Issue by rasky** [AlexLittlejohn/ALCameraViewController#119]
One issue with square crops is that you're always forced to take out a portion of a picture that was taken for the phone; think of a picture of a leaflet (portrait or landscape): whatever crop area you select, a portion of the text of the leaflet will be taken out.

Assuming a situation in which the backend requires square pictures anyway, one solution would be to allow the user to create a square that is *larger* than the picture, adding black bands to fill in portions outside the picture. This would also be very natural from an UX POV, as the user would simply be allowed to enlarge the crop square past the limits of the picture itself.

**Comment by AlexLittlejohn** [comment]
This is not something I am planning to add. However if enough people want it I may reconsider, but it would have to be able to be toggled off because it is not desirable behavior in most cases.
