### ISSUE TITLE
Cannot load picture gallery

### ISSUE THREAD

**Issue by noctivityinc** [AlexLittlejohn/ALCameraViewController#12]
Not sure if this is related to the simulator or not, but when I click "Camera" then Photo Library the app crashes and I get:

fatal error: unexpectedly found nil while unwrapping an Optional value  and the issue appears to be in the stopSession function:

    public func stopSession() {
        if session != nil {
            dispatch_async(cameraQueue) {
                self.session.stopRunning()
                self.preview.removeFromSuperlayer()  <-- THIS IS THE LINE

**Comment by AlexLittlejohn** [comment]
The iOS simulator doesn't have camera functionality and will crash when trying to use any app that requires it.
