### ISSUE TITLE
No zooming enabled?

### ISSUE THREAD

**Issue by bkrijgsman** [AlexLittlejohn/ALCameraViewController#120]
Hi,

The ALCameraViewController works perfect! It's really nice. But we have found a bug / maybe?
On a jailbroken device, it looks like zoom enabling doesn't work. If you select a photo from the album or directly create a foto and zoom it afterwards, our code will find the original image instead of the zoomed/cropped image.

`
let cameraViewController = CameraViewController(croppingEnabled: true) { image in            
if let image = image.0 {
         //Here we are sending the image to the server.
    }
}
`

Am i doing something wrong or is this a bug which appears on a jailbroken iPhone? :)

**Comment by AlexLittlejohn** [comment]
The camera component itself doesn't support zoom. If you are referring to the screen afterwards, if you have not enabled cropping then it doesn't do anything when you pan and zoom the image.
