### ISSUE TITLE
Camera not working for iPod touch 5 without rear camera.

### ISSUE THREAD

**Issue by bhavukjain1** [AlexLittlejohn/ALCameraViewController#121]
Whenever I call this completion block:
 let cameraViewController = CameraViewController(croppingEnabled: croppingEnabled, allowsLibraryAccess: libraryEnabled) { [weak self] image, asset in
            self?.imageView.image = image
            self?.dismissViewControllerAnimated(true, completion: nil)
        }
        
        presentViewController(cameraViewController, animated: true, completion: nil)

It opens the camera but doesn't show any image.
![img_1630](https://cloud.githubusercontent.com/assets/15347380/17062279/ed2184b2-504f-11e6-8585-5ae3a9a43d6e.PNG)

**Comment by AlexLittlejohn** [comment]
This is most likely because it opens the rear camera by default. There is a request to have this be configurable in a future release.

**Comment by AlexLittlejohn** [comment]
I've added the ability to make the front camera the default in 1.2.3
