### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Tulleb** [AlexLittlejohn/ALCameraViewController#122]
Thanks a lot for this library @AlexLittlejohn!

Could you create a Swift 3 branch please?
I am about to submit a PR for Xcode 8 compatibility.

PS: Love your Tiny picture btw :)

**Comment by AlexLittlejohn** [comment]
I'm glad you're a fan of tiny as well. 

I have a swift 3 branch already on my local. I will push it shortly.

**Comment by Tulleb** [comment]
Is it the one called `feature/XCode8`? Do you want me to do the #124 again for this branch then?

**Comment by AlexLittlejohn** [comment]
I'll be merging/testing #125 into develop soon and then merge develop into `feature/XCode8` when i'm done.

**Comment by Tulleb** [comment]
Ok. Just to let you know @AlexLittlejohn, Xcode 8 Beta 6 was released yesterday with (at least) 11 new issues to fix. I am updating the PR at the moment...
