### ISSUE TITLE
ios 10 session.sessionPreset = AVCaptureSessionPresetPhoto crash

### ISSUE THREAD

**Issue by AfnanMirza1999** [AlexLittlejohn/ALCameraViewController#139]
so every time i try to open the camera in the app the app crashes at line 107 i am using xcode 8 and ios 10

    private func createSession() {
        session = AVCaptureSession()
        session.sessionPreset = AVCaptureSessionPresetPhoto
        DispatchQueue.main.async() {
            self.createPreview()
        }
    }

**Comment by AlexLittlejohn** [comment]
Are you using the simulator?

**Comment by AfnanMirza1999** [comment]
yes

**Comment by AlexLittlejohn** [comment]
You cannot use the camera on a simulator. You'll have to test on a real device
