### ISSUE TITLE
App crashing as soon as cropping switch is selected

### ISSUE THREAD

**Issue by tomshanks** [AlexLittlejohn/ALCameraViewController#141]
Hi Alex,

I was trying your app on an iPhone 6 loading from XCode version 8.0. The app loads with the Library Access switch on and the Cropping switch set to off. If I try and switch the cropping switch to on the app crashes immediately. XCode states,  ALCameraViewController[408:23708] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ALCameraViewController.ViewController croppingChanged:]: unrecognized selector sent to instance 0x100c09290'

Just wondered if you're aware of this issue. If I manage to debug I will post a solution.

Regards,

Tom

**Comment by AlexLittlejohn** [comment]
Fixed. Thank you for pointing this out.
