### ISSUE TITLE
Can't compile with Swift 3

### ISSUE THREAD

**Issue by damirdjozic** [AlexLittlejohn/ALCameraViewController#142]
I added this framework using pod install, but I get 122 errors. Installed version is 1.2.5. What should I do?
I updated project to swift 3, and updated Xcode 7 to Xcode 8.

Here is the pod file:
platform :ios, '10.0'
target 'ProjectName' do
    pod 'ALCameraViewController'
end

**Comment by gslopez** [comment]
+1 same issue

**Comment by AlexLittlejohn** [comment]
Mmake sure you have the latest version of the cocoapods (earlier versions may not honour the pod swift version)

**Comment by gslopez** [comment]
Fixed !
I ran "pod repo update" before "pod install" and worked.
Thanks!
