### ISSUE TITLE
Persistent store error

### ISSUE THREAD

**Issue by mkeremkeskin** [AlexLittlejohn/ALCameraViewController#143]
With iOS 10 after taking a photo library gives the error below. Why this is happening do you have any ideas?

> [error] error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///var/mobile/Media/PhotoData/Photos.sqlite?readonly_shm=1 options:{
    NSPersistentStoreFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
    NSReadOnlyPersistentStoreOption = 1;
    NSSQLitePersistWALOption = 1;
    NSSQLitePragmasOption =     {
        "journal_mode" = WAL;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={reason=Failed to access file: 1} with userInfo dictionary {
    reason = "Failed to access file: 1";
}
[Migration] Unexpected error opening persistent store <private>, cannot attempt migration <private>)
[Migration] Failed to open store <private>.  Requires update via assetsd (256: <private>)
[error] error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///var/mobile/Media/PhotoData/Photos.sqlite?readonly_shm=1 options:{
    NSPersistentStoreFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
    NSReadOnlyPersistentStoreOption = 1;
    NSSQLitePersistWALOption = 1;
    NSSQLitePragmasOption =     {
        "journal_mode" = WAL;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo={reason=Failed to access file: 1} with userInfo dictionary {
    reason = "Failed to access file: 1";
}
[Migration] Store open/configuration failed on 2nd attempt: <private>

**Comment by AlexLittlejohn** [comment]
It seems you found a bug in apples PhotoKit framework. If you can reproduce it reliably then i would suggest you file a bug report on their radar.
