### ISSUE TITLE
IOS 10 minimum target support

### ISSUE THREAD

**Issue by Andrewangeta** [AlexLittlejohn/ALCameraViewController#145]
Basically AVCaptureStillImageOutput is deprecated and AVCapturePhotoOutput has delegation now. Any plans to make this iOS 10 supported?

![screen shot 2016-09-28 at 6 11 05 pm](https://cloud.githubusercontent.com/assets/12012815/18935629/f21710e0-85a6-11e6-8c46-eb475a3e1c25.png)

**Comment by AlexLittlejohn** [comment]
It still works on iOS 10. Dropping `AVCaptureStillImageOutput` would leave iOS 8 - 9 without options

**Comment by davidseek** [comment]
but those warnings lead to re-compile of the whole project every build and that, also is no option

**Comment by davidseek** [comment]
@avaibleios10 blah would do it...
