### ISSUE TITLE
after upgarde to xcode8 - opening camera crashes

### ISSUE THREAD

**Issue by rachellelancer** [AlexLittlejohn/ALCameraViewController#149]
Thanks for the great pod!

I upgraded to xcode8 using swift 2.3 and started crashing when opening the camera.
(sometimes you need to start/stop/start to see the crash)

The exception error is:
_This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes._

The problem is around the call to self.session?.startRunning() in an async background queue.
Commenting out dispatch_async(cameraQueue) fixed the crash but probably not healthy.

public func startSession() {
        dispatch_async(cameraQueue) {
            self.createSession()
            self.session?.startRunning()
        }
    }

**Comment by AlexLittlejohn** [comment]
Make sure you are using the latest version of the library

**Comment by rachellelancer** [comment]
right, I just realised that.

Since you were kind enough to reply, I have a problem.
I cant update the pod becuase I didnt upgrade to Swift3 since other pods
that we rely on are not up to date yet.

Is there an intermediate work around?

Thanks

**Comment by AlexLittlejohn** [comment]
I think your best bet would be to for you to fork/clone this repo at the last swift 2.3 compatible version (1.2.4 I think) and then mirror fixes in startSession to your copy. Currently there is no way to have both 2.3 & 3.0 in the same project.

**Comment by rachellelancer** [comment]
Thanks so much for your quick response.

Yes. Pretty much sums it up that I need to move over to swift 3.
If only all pods were up to date like ALCamera ...

With much appreciation,
Rachelle

**Comment by townsendeb** [comment]
Im having the same issue in Swift 3, Xcode 8. The camera simply will not open. It's not really showing an error, just crashing. I'll screenshot what the side part says so you can see if you see the issue. Im running 1.2.6 by the way.

![image](https://cloud.githubusercontent.com/assets/16887846/19357274/89f3a87a-9136-11e6-8c93-94640a82d804.png)

**Comment by LukA888** [comment]
Did you find a solution? I'm facing the same problem :/

**Comment by townsendeb** [comment]
I was trying to run it on a simulator and not on a physical device, thats why it wasnt working

**Comment by HengdaXiao** [comment]
Same here. Swift 2.3. Maybe need to upgrade to Swift 3.
