### ISSUE TITLE
Custom rectangular shape crop 

### ISSUE THREAD

**Issue by driver733** [AlexLittlejohn/ALCameraViewController#15]
Hi!
Are there any plans to make the cropper to take a custom rectangular shape, rather than a simple square? Also, it would great to add the ability to rotate an image (like in "Edit" mode in "Photos" app).

**Comment by apache2046** [comment]
Yes, these missing features are very important !!!

**Comment by ServicePal** [comment]
Would be nice if we could pass in arguments for the cropper view area size, like 360 x 700, 120 x 800.
Perhaps even a circular option, if someone would like to use it for avatar capture.

**Comment by mrigdon** [comment]
Was just about to say what @ServicePal just said. I see it's easy to change the dimensions of the crop box in ALCameraViewController::layoutCropView(), but can't figure out how to handle the rest.

For those who would like to help out here's what I've done so far (original code commented):

```swift
// in ALCameraViewController::layoutCropView()
//let width = minDimension - horizontalPadding
//let height = width
let width = UIScreen.mainScreen().bounds.size.width
let height = width * (2/3) // I need a 2/3 dimensioned rectangle
//let x = horizontalPadding/2
let x: CGFloat = 0
```

also set the member variable
```swift
// ALCameraViewController member variable
//var horizontalPadding: CGFloat = 30
var horizontalPadding: CGFloat = 0
```

But that's as far as I can manage to get.

**Comment by stachon** [comment]
+1 for this. I have some code for this https://github.com/stachon/ALCameraViewController/tree/custom_overlay but it fails to display the crop view in ConfirmView. Probably needs to add layout code.

**Comment by subhashisrouth** [comment]
You can look at cordova-plugin-crop Cordova plugin and view their source code, they implemented it.

**Comment by Tulleb** [comment]
If you are already using Swift 3, this issue should be fixed by PR #124.

Meanwhile it's being accepted and merged by @AlexLittlejohn, you can use my fork repository with CocoadPod line:
`pod 'ALCameraViewController', :git => 'https://github.com/Tulleb/ALCameraViewController.git', :branch => 'swift3'`

**Comment by mrigdon** [comment]
@Tulleb not compatible with swift 2.x tho?

**Comment by Tulleb** [comment]
No @mrigdon I didn't need it but I can submit another PR for it if some of you need.

**Comment by Tulleb** [comment]
@mrigdon I just did the PR for Swift 2.x.

You can check it out by setting your Pod line to this:
`pod 'ALCameraViewController', :git => 'https://github.com/Tulleb/ALCameraViewController.git', :branch => 'develop'`

It might still need some improvement but I think it's already a good start :)

**Comment by Tulleb** [comment]
There is still an issue when the original image doesn't fit in the device screen. I'll try to check it out later...

**Comment by bagwanshoaib** [comment]
did you find solution for custom rectangular shape crop???

**Comment by Tulleb** [comment]
Well @bagwanshoaib my PR is working quite fine at the moment. There's still some issues to fix yet but they're minor imo.

**Comment by bagwanshoaib** [comment]
Can you suggest any custom solution for that please?

**Comment by Tulleb** [comment]
As I said above @bagwanshoaib, if you are using CocoaPod, you can set this line and comment your current one:
`pod 'ALCameraViewController', :git => 'https://github.com/Tulleb/ALCameraViewController.git', :branch => 'develop'`

**Comment by bagwanshoaib** [comment]
I am sorry i am not getting to you, after updating my pod link what code changes i should make to crop image in rectangular shape?

Thanks for your quick reply

**Comment by Tulleb** [comment]
@bagwanshoaib nothing especially. The user will be able to change the cropped shape by himself by dragging the corners.

**Comment by joekw** [comment]
@Tulleb How can i specify some dimensions for the crop without allowing the user to change it?

**Comment by Tulleb** [comment]
@joekw My branch doesn't let the user do that. The user can only crop the picture with gestures after taking it.
You should fork my branch and code this development by yourself I guess. Or ask @AlexLittlejohn to add this feature maybe.

Good luck!

**Comment by joekw** [comment]
@Tulleb I've had a look and it seems beyond my skill level to be honest. Oh well.

**Comment by Tulleb** [comment]
@joekw Yeah I think it's one of the possibilities to do that.
Try to find the code line where I am cropping the photo (after the user pressed the OK button I guess), and replace the variable by the crop rect you want.

**Comment by leminhtuan2015** [comment]
@Tulleb the branch pod 'ALCameraViewController', :git => 'https://github.com/Tulleb/ALCameraViewController.git', :branch => 'swift3'
is so slow when open camera, please tell me ho to solve this.

**Comment by Tulleb** [comment]
@leminhtuan2015 I will take a look at it asap and make a fix on the branch.

**Comment by leminhtuan2015** [comment]
@Tulleb Thank sir So much, I am waiting for your new update. 
The function "Custom rectangular shape crop" in the branch swift3 is so helpful for me but this branch open camera so slow. Cause of that now I have to use "pod 'ALCameraViewController'" without  "Custom rectangular shape crop"

Please help me fix soon so that I can use your swift3 branch

Thank sir so much!

**Comment by Tulleb** [comment]
@leminhtuan2015 done dude.

You can now fork the master branch of pod 'https://github.com/Tulleb/ALCameraViewController.git' while @AlexLittlejohn merge the PR.

`pod 'ALCameraViewController', :git => 'https://github.com/Tulleb/ALCameraViewController.git'`

**Comment by leminhtuan2015** [comment]
@Tulleb : It work so great now!  You are the best guy, You help so so much.  Thank sir.

**Comment by Fengson** [comment]
Just to let you know, cropping @Tulleb doesn't work well.
There should be a constraint that prevents moving the overlay outside of the image bounds. Otherwise, many issues arise and cropping doesn't work if overlay consists of the area outside of the image bounds. And you can never expect what a user would do :)

Any idea on patching this?

**Comment by Tulleb** [comment]
@Fengson The way I am using it in my app (full screen photo), the user doesn't have any issue with it.

Feel free to propose a fix on my fork. I will gladly look for it. But meanwhile I'm sorry, I don't have enough time to check about it...
