### ISSUE TITLE
Focus to point does not works properly - with fix

### ISSUE THREAD

**Issue by rogomantik** [AlexLittlejohn/ALCameraViewController#150]
public func focusCamera(toPoint: CGPoint)
change

//        let focusPoint = CGPoint(x: toPoint.x / frame.width, y: toPoint.y / frame.height)
        **let focusPoint = self.preview.captureDevicePointOfInterestForPoint(toPoint)**
 if device.focusPointOfInterestSupported {
            device.focusPointOfInterest = focusPoint
        }

the old focusPoint is calculated from top left 0,0 to bottom right 1,1 of the screen

captureDevicePointOfInterestForPoint
Form documentation
The coordinates in the point structure returned by this method are in the range 0.0 to 1.0. The point (0.0, 0.0) corresponds to the top left corner of the **unrotated picture** and the point (1.0, 1.0) represents the bottom right corner of the unrotated picture

I think is something related to unrotated picture
You can use and check for focusPointOfInterestSupported or calculate focusPoint according to the one returned by captureDevicePointOfInterestForPoint. Just print(oldFocusPoint) and print(focusPoint)

**Comment by AlexLittlejohn** [comment]
Thank you for this. I've added it to the current development branch.
