### ISSUE TITLE
SWIFT 2.3

### ISSUE THREAD

**Issue by IOSPUNIT** [AlexLittlejohn/ALCameraViewController#151]
HELLO ALEX,
i am using alcameraView controller in swift 2.3 for ios 10 but its doesn't work properly. New latest code in swift 3.0 but i can't use this updated code becoze my code in swift 2.3 please provide swift 2.3 version.
contact: punit.kumar@mobulous.com
thanks & regards 
punit

**Comment by AlexLittlejohn** [comment]
Unfortunately there are no plans to add this. If you want you can submit a PR with this.
