### ISSUE TITLE
Swift 3 update

### ISSUE THREAD

**Issue by FaridHaddad** [AlexLittlejohn/ALCameraViewController#153]
Hello,

It is still not compatible with swift 3 syntax.
When will this be ok ?

Thank you,
Farid

**Comment by AlexLittlejohn** [comment]
Use the latest cocoa pods beta version to install the pod and make sure you are using the latest version

**Comment by FaridHaddad** [comment]
And what is the latest cocoapods version ?

**Comment by alexandrlich** [comment]
@FaridHaddad  I just realized that something's lacking the documentation based on this comment.

If you use latest stable version 1.0.1 - it doesn't work.

You need to do: sudo gem install cocoapods --pre
to install 1.1.0.rsSOMETHING

**Comment by FaridHaddad** [comment]
when i add pod 'ALCameraViewController','1.1.0' or '1.2.7' or without specifying, it tells to me convert to swift 3 syntax.

**Comment by AlexLittlejohn** [comment]
Use 'sudo gem install cocoapods --pre' to install the latest version of cocoapods and then try again. Also note that the library requires swift 3

**Comment by FaridHaddad** [comment]
okay will do so now thank you

**Comment by FaridHaddad** [comment]
thank you this worked for me.

**Comment by nodox** [comment]
Confirmed: `sudo gem install cocoapods --pre` solves the SWIFT_LEGACY error
