### ISSUE TITLE
Amateurish framework 

### ISSUE THREAD

**Issue by San-Jeevan** [AlexLittlejohn/ALCameraViewController#154]
I used this in an app for submitting photos taken by the user.
Turns out half my customerbase quits the application when they receive the "photo library access"-permission dialog.

Why not just pass the image object directly back instead of storing in photo library.

Really amateurish

**Comment by ppamorim** [comment]
We `really` don't care about it.

Your application, your problems. If your application is not good enough to gain the confidence of your user, this problem is not related with the library.

Bye.

**Comment by AlexLittlejohn** [comment]
Thank you for your comments.

If you would like some alternatives 

- https://github.com/hyperoslo/ImagePicker 
- https://github.com/ytakzk/Fusuma

Lastly I would suggest that you add a clear `NSPhotoLibraryUsageDescription` key to your info plist.
