### ISSUE TITLE
1.2.6 branch not working with swift 3

### ISSUE THREAD

**Issue by alexandrlich** [AlexLittlejohn/ALCameraViewController#155]
When i installed pod (i also tried to specify 1.2.6 version) i see in logs
"Installing ALCameraViewController (1.2.6)"

However when I open the workspace it says ALCameraViewController module needs to be updated to the latest version.
After I did I get a compilation error(attached the screenshot)
<img width="841" alt="screen shot 2016-10-16 at 1 33 56 am" src="https://cloud.githubusercontent.com/assets/16494985/19415534/0456f638-9341-11e6-886b-ebe24c644af3.png">

**Comment by AlexLittlejohn** [comment]
Please ensure you are using the latest version of cocoapods as the library definitely supports swift 3

**Comment by alexandrlich** [comment]
I am sorry but latest 1.2.7 version doesn't work either. This time after I installed version 1.2.7 it told me I need to convert ALCameraViewController module to swift 3.0 and after that I get 287 compilation errors in this module.

I use xcode 8 cocoapods 1.0.1, I tried to upgrade everything to latest version just to be sure.
Our code runs on swift 3

**Comment by alexandrlich** [comment]
There was 1 warning during the installation:
pod update
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/imagemagick/bin in PATH, mode 040777
Update all pods
Updating local specs repositories

CocoaPods 1.1.0.rc.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.3

Analyzing dependencies
Downloading dependencies
Installing ALCameraViewController (1.2.7)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] The `FoodSpy [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-FoodSpy/Pods-FoodSpy.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

I added inherited flag and it removed the warning(see http://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods for more details)

**Comment by alexandrlich** [comment]
@AlexLittlejohn  I just realized what the solution is:
If you use latest stable version 1.0.1 - it doesn't work.

You need to do: sudo gem install cocoapods --pre
to install 1.1.0.rsSOMETHING
