### ISSUE TITLE
installation documentation: additional details

### ISSUE THREAD

**Issue by alexandrlich** [AlexLittlejohn/ALCameraViewController#156]
Hi.
I thought the following might be useful for people using this module

1. Specify cocoapod version(it doesn't work with the latest stable version 1.0.1 and only works with 1.1.0 rc version)

2. After opening xcode you need to add the following header to your bridge file(or create one if you don't have any)
#import <ALCameraViewController/ALCameraViewController-Swift.h>

Without those 2 steps ALCameraViewController didn't work for me at all...

Thanks, hope you find it useful.

**Comment by AlexLittlejohn** [comment]
Step 2 is only required if you don't specify `use_frameworks!` in your pod file.

**Comment by alexandrlich** [comment]
I had use_frameworks! specified and still had to do it.
