### ISSUE TITLE
Error: Cannot Record

### ISSUE THREAD

**Issue by JasonGreenAmerica** [AlexLittlejohn/ALCameraViewController#16]
self.preview.removeFromSuperlayer()
Error: Cannot Record
fatal error: unexpectedly found nil while unwrapping an Optional value

public func stopSession() {
        if session != nil {
            dispatch_async(cameraQueue) {
                self.session.stopRunning()
                self.preview.removeFromSuperlayer()
                
                self.session = nil
                self.input = nil
                self.imageOutput = nil
                self.preview = nil
                self.device = nil
            }
        }
    }

**Comment by AlexLittlejohn** [comment]
Run the app on a device, not the simulator (which has no camera)
