### ISSUE TITLE
How can I change the crop size from 1:1 to 16:9 or 3:2?

### ISSUE THREAD

**Issue by nalogowiec** [AlexLittlejohn/ALCameraViewController#169]
Guys, great plugin! Currently I'm struggling with changing the aspect ration of crop area from 1:1 to 3:2 or 16:9, so far with no luck - can you suggest me any changes in the code to fix that?

**Comment by AlbertoMrFz** [comment]
I want the same

**Comment by AlbertoMrFz** [comment]
Agree, would be super useful if we can set any crop size. Seems being bound to a square photo is super limiting.

**Comment by LiborZ** [comment]
I want to change UIImagePickerController because I want to change crop size aspect ratio. So this feature would be really great.

**Comment by AlbertoMrFz** [comment]
Hi, you can use that pod: WDImagePicker

**Comment by agordeev** [comment]
That'd be very great feature! Only lacking of that functionality stops me from using this library.
