### ISSUE TITLE
camera view on half of the screen

### ISSUE THREAD

**Issue by sumeet0710** [AlexLittlejohn/ALCameraViewController#180]
Can I reduce the frame of camera view to the half of the screen and half of the screen will have image gallery. see below screenshot.
<img width="261" alt="screen shot 2017-02-02 at 4 50 05 pm" src="https://cloud.githubusercontent.com/assets/25523104/22581739/39a39908-ea1d-11e6-8063-821b91b18c92.png">

Please help me ASAP. Thank you.

**Comment by AlexLittlejohn** [comment]
Have a look a [Fusuma](https://github.com/ytakzk/Fusuma)
It looks a lot more like your example. Maybe it would suit your needs?
