### ISSUE TITLE
Don't save photo to camera roll

### ISSUE THREAD

**Issue by Vaberer** [AlexLittlejohn/ALCameraViewController#186]
Is there a way how to disable saving photos to camera roll after capturing a photo?

**Comment by Vaberer** [comment]
If you have any hints how to achieve it in the code, I will be more than glad.
Thanks

**Comment by daviskoh** [comment]
+1

**Comment by albedo83** [comment]
+1 i really need it please

**Comment by albedo83** [comment]
help :')

**Comment by AlexLittlejohn** [comment]
Available in 1.4.0

**Comment by suadbay** [comment]
To disable saving the taken photo to camera roll add this: "allowsLibraryAccess: false"

let cameraViewController = CameraViewController(allowsLibraryAccess: false) { [weak self] image, asset in
	// Do something with your image here.
	self?.dismiss(animated: true, completion: nil)
}

present(cameraViewController, animated: true, completion: nil)
