### ISSUE TITLE
Camera Accessing Slow 

### ISSUE THREAD

**Issue by robertvishal** [AlexLittlejohn/ALCameraViewController#189]
in my app I used AlcameraViewController. It is slow in accessing camera in iOS 10.The camera become open after about 15 seconds.But in iOS 9 it works correctly. Help me to solve this

**Comment by picturehit** [comment]
Hello everyone.
Same problem.
Has anybody a solution ? 
Thank you !

**Comment by picturehit** [comment]
Sorry no problem after updating the library !
Good work !

**Comment by ncntechnology** [comment]
ok.fine. I updated and change some code segments.Its working for me.
