### ISSUE TITLE
It cant go back to previous screen (if that screen is not root)

### ISSUE THREAD

**Issue by MZS1207** [AlexLittlejohn/ALCameraViewController#190]
It does not return to previous screen. 
It go back to root and user if add photo cant see it till scoll back to. 
Cant be solved or its just made like that?

**Comment by AlexLittlejohn** [comment]
I'm not sure what you mean. Could you make a diagram perhaps of what you are experiencing or your expected flow?

**Comment by Tykhonkov** [comment]
*version* ALCameraViewController (1.3.1)
*device* ip6s 10.3.1, simulator ip7 10.3

*steps:*
# open camera
# tap on a cancel button 
# camera is hidden
# open camera
# tap on a cancel button 

*result:* 
nothing happen

*expected:*
camera is hidden

**Comment by vCrespoP** [comment]
Same here, even on the first execution. Code c&p from your sample, so using "present" method on the view Controller. Hitting the 'x' to close the view does nothing.
