### ISSUE TITLE
add Localization to Russian language

### ISSUE THREAD

**Issue by Dronnn** [AlexLittlejohn/ALCameraViewController#196]
Hi! 
Could you please add new localization (Russian language)? 
Or please explain me how can I add it by myself?

here is translation

"Permissions.title" = "Доступ к камере запрещен";
"Permissions.description" = "Включите доступ к камере в настройках конфиденциальности";

"Permissions.library.title" = “Доступ к библиотеке фотографий запрещён”;
"Permissions.library.description" = "Включите доступ к библиотеке фотографий в настройках конфиденциальности";

"Permissions.settings" = "Настройки";

"Error.cant-fetch-photo" = "Не удалось получить изображение";
"Error.cant-fetch-photo.description" = "Проверьте сетевые настройки";

**Comment by AlexLittlejohn** [comment]
You can already achieve this without modifications.
1. Create a localised `CameraView.strings` file in your project
2. Insert your strings into the new .strings file
3. ...
4. Profit 🏅 

The library will already look for a strings file in your own project first before falling back to the included one. 

Note that you may have to copy over the english translations if you still want to use them.

**Comment by Dronnn** [comment]
Thanks for your answer :)

this method was first that I had tried
but, unfortunately, it doesn't works

you determine bundle like that
NSLocalizedString(... bundle: CameraGlobals.shared.bundle ...

but it is not in app bundle
(lldb) po CameraGlobals.shared.bundle
NSBundle </var/containers/Bundle/Application/.../Frameworks/ALCameraViewController.framework> (loaded)

what is my mistake?

**Comment by Dronnn** [comment]
@AlexLittlejohn

**Comment by AlexLittlejohn** [comment]
Make sure you are using the latest version of the library

**Comment by Dronnn** [comment]
@AlexLittlejohn 
OMG! 
I've forgot update the library. 
Thanks! Many-Many thanks! It works.

I'm sorry to trouble you.
