### ISSUE TITLE
Open gallery without giving camera access permissions

### ISSUE THREAD

**Issue by crc1559** [AlexLittlejohn/ALCameraViewController#198]
Is it currently possible to allow the user to select a picture without using the camera if they decline to give access to the camera?

Steps:
Open ALCameraViewController -> Request Camera Permission -> Permission denied -> User is locked out and told to change their settings.

What I would like:
Open ALCameraViewController -> Request Camera Permission -> Permission denied -> User presses button to go to gallery -> Request Gallery Permission -> access gallery

**Comment by AlexLittlejohn** [comment]
Apologies for the late reply, you can create the image picker directly without requesting camera access. Have a look at the readme which outlines the process.
