### ISSUE TITLE
Landscape?

### ISSUE THREAD

**Issue by DenisDbv** [AlexLittlejohn/ALCameraViewController#2]

**Comment by jasan-s** [comment]
Any way to customize crop square to custom ration ?

**Comment by jasan-s** [comment]
Also, yeah landscape?

**Comment by AlexLittlejohn** [comment]
I am working on this feature and it will be added to the repo soon™

**Comment by jasan-s** [comment]
awesome!

**Comment by jasan-s** [comment]
quick question. I am total newbie. Is it possible to adjust the crop ratio in the code?

**Comment by AlexLittlejohn** [comment]
Not at the moment. For now its square crops or no cropping.

**Comment by jasan-s** [comment]
If I lock the app just on portrait mode and take a picture the resulting image is sideways, is there a way to detect if the device was oriented in landscape even though the app is locked to portrait mode and rotate the captured image right way .

**Comment by JordanRoPo** [comment]
bump, @jasan-s 's question, cause I would very much like to implement this!
