### ISSUE TITLE
naughty indicator view

### ISSUE THREAD

**Issue by wadevanne** [AlexLittlejohn/ALCameraViewController#204]
![wechatimg49](https://user-images.githubusercontent.com/13325485/27377390-61556e1c-56a7-11e7-8d03-9dd02e07d816.jpeg)
![wechatimg51](https://user-images.githubusercontent.com/13325485/27377396-655bf706-56a7-11e7-8a8f-1eeb8c2c8f9c.jpeg)
before layout subviews

**Comment by AlexLittlejohn** [comment]
Please test the library on a real device.
