### ISSUE TITLE
Status Bar Not Hidden when CameraViewController open the camera 

### ISSUE THREAD

**Issue by udayasri** [AlexLittlejohn/ALCameraViewController#207]
Hi, 

I have added the library to my project through CocoaPods and when I access the CameraViewController it opens the camera. but it has the status bar enabled.
I can see this in CameraViewController too. 

```
open override var prefersStatusBarHidden: Bool {
        return true
 }
```
I have this in my info.plist 
`View controller-based status bar appearance: No`

Any idea of how to hide it ? I'm checking this with iPhone 7 iOS 10.3.2

![image](https://user-images.githubusercontent.com/1368143/28300424-fe1ba0f4-6b9c-11e7-9fb0-6d8984a5e093.png)

**Comment by AlexLittlejohn** [comment]
You will need to change the plist value to allow view controllers to control the status bar appearance
`View controller-based status bar appearance: YES`
