### ISSUE TITLE
hiding status bar

### ISSUE THREAD

**Issue by muh-azharudheen** [AlexLittlejohn/ALCameraViewController#208]
when i cliking a button to go to camera view controller. my present view controller shaking and hides the status bar and cause some problems to shadow to that button

any one help

**Comment by muh-azharudheen** [comment]
problem when using from a viewcontroller embeded in navigation controller

**Comment by AlexLittlejohn** [comment]
Do you have any screenshots to better describe the issue? I can't make out the details from what you've provided.
