### ISSUE TITLE
Getting Warning in iOS 10.3

### ISSUE THREAD

**Issue by joprithiviraj** [AlexLittlejohn/ALCameraViewController#212]
Every thing working fine but its showing more then 10 warning in xcode 8.3.2. Can you please update it. Thanks in advance.

**Comment by AlexLittlejohn** [comment]
What warnings are you getting? Also there is a newer version of Xcode available. Have you tried updating to it?

**Comment by joprithiviraj** [comment]
If iOS Deployment Target is 10.1 to latest version, getting warning like " 'AVCaptreStillImageOutput' was deprecated in iOS 10.0: Use AVCapturePhotoOutput instead". Thanks in Advance

**Comment by AlexLittlejohn** [comment]
Ah yes, there is a new camera API, however it is available on iOS 10 and up only. Since we still want to support iOS 8 users we maintain usage of the older camera apis.
