### ISSUE TITLE
How can I crop the image that I already have the image path? 

### ISSUE THREAD

**Issue by Chhuon** [AlexLittlejohn/ALCameraViewController#213]
I already have the image selected and I already have its path. I want the library work for cropping only, meaning that I don't want `ALCameraViewController` browse the image from Photo library. Is there any way out for this?

**Comment by AlexLittlejohn** [comment]
Its reasonably complicated to achieve this without delving into the Photos framework. I suggest looking at another library instead: https://github.com/TimOliver/TOCropViewController. This library is a dedicated image cropping tool.
