### ISSUE TITLE
Cancel button throw error

### ISSUE THREAD

**Issue by ing4prg** [AlexLittlejohn/ALCameraViewController#215]
If Cancel button is clicked on CameraViewController (bottom left button), then a fatal error is thrown:
"fatal error: unexpectedly found nil while unwrapping an Optional value"

I tested it on iPhone SE.

**Comment by MrAngrez** [comment]
same error if you get solution then please contact me

**Comment by AlexLittlejohn** [comment]
Both the image and the asset will be `nil` if a user selects cancel. 
Ensure that you are checking for the presence of `nil` in your completion block.
