### ISSUE TITLE
issue when migrating to swift4

### ISSUE THREAD

**Issue by ashish-naik** [AlexLittlejohn/ALCameraViewController#229]
i am trying to convert my project to Swift 4. However, get to screens shown in attached screenshots.

How to resolve this? I am using Cocoapod so don't want to manually manage the framework code.

Thanks
Ashish

![utilities](https://user-images.githubusercontent.com/4936420/31015537-4ea033c0-a53e-11e7-8236-5a5859d374a0.png)
![cameraglobals](https://user-images.githubusercontent.com/4936420/31015538-4ea18cc0-a53e-11e7-84f2-afc10c120a04.png)

**Comment by AlexLittlejohn** [comment]
Please upgrade your pod to the latest version (3.0.1), and exclude it from your migration

**Comment by ashish-naik** [comment]
Hi Alex,

I have already migrated to 3.0.1 and if i exclude from migration then xcode gives this message.

![exclude message](https://user-images.githubusercontent.com/4936420/31021986-1c492640-a555-11e7-85f4-5339c9c5250b.png)

**Comment by AlexLittlejohn** [comment]
3.0.1 is not swift 4?

**Comment by ashish-naik** [comment]
I am sorry didnt understand!! Project  Release page says 3.0.1. is migrated to Swift4

**Comment by ashish-naik** [comment]
Alex,

When xcode presented the window with changes suggested ( as shown in first two screenshots), i deselected both files and went ahead without accepting Xcode suggestion. My project then converted to Swift 4.

Believe this was the the right thing !!

Will post if i face any issue.

Thanks
Ashish
