### ISSUE TITLE
Swift 4.0 errors

### ISSUE THREAD

**Issue by darko55s** [AlexLittlejohn/ALCameraViewController#230]
<img width="285" alt="screen shot 2017-09-29 at 8 35 01 pm" src="https://user-images.githubusercontent.com/10081234/31030499-da575d32-a555-11e7-9092-ed33c3d30ae2.png">

Can we get quick fix and update for this one?

**Comment by sabiland** [comment]
I have the same problems.

**Comment by AlexLittlejohn** [comment]
Which version of the framework are you using?

**Comment by sabiland** [comment]
I am starting to replace AVMediaType.video -> AVMediaTypeVideo, etc.

This is the only one left I need to fix:

```
private func cameraWithPosition(position: AVCaptureDevice.Position) -> AVCaptureDevice? {
        let devices = AVCaptureDevice.devices(withMediaType: AVMediaTypeVideo)
        
        
        // This line not ok
        return devices.filter { $0.position == position }.first
    }
```

**Comment by darko55s** [comment]
@AlexLittlejohn i am using 3.0.1 the latest instaled by Pods

**Comment by UtkuDalmaz** [comment]
I have same problems with 3.0.1
<img width="257" alt="screen shot 2017-10-01 at 18 29 33" src="https://user-images.githubusercontent.com/2130592/31056190-814a5fe6-a6d6-11e7-98aa-c9602992c594.png">

**Comment by sabiland** [comment]
As I wrote before, this few erros can easily be fixed. 

Replace AVMediaType.video -> AVMediaTypeVideo

etc.

**Comment by karishmapujara** [comment]
I have the same problems with 3.0.1 and xcode 9.0

**Comment by AlexLittlejohn** [comment]
@sabiland your fix indicates that you have not migrated your project to swift 4.0 yet.

`AVMediaTypeVideo` became `AVMediaType.video` in swift 4.0

If you still need to use it with swift 3 then please link your project against version 2.0.* in your pod file

**Comment by sabiland** [comment]
You are right. I've migrated to Swift 4 and everything is ok now!
