### ISSUE TITLE
Crop overlay is preventing spot focus/exposure setting

### ISSUE THREAD

**Issue by Dlemex** [AlexLittlejohn/ALCameraViewController#231]
The current release breaks the ability to tap in the camera view to adjust exposure/focus settings.  If you tap outside the overlay, spot features still work.  Taps that are not crop related need to be passed on to the AV device.

My workaround to restore the old functionality was to restore `isUserInteractionEnabled = false` to the createLines function in CropOverlay.

**Comment by AlexLittlejohn** [comment]
Fixed in v3.0.2
