### ISSUE TITLE
Getting compiler errors in version 3.0.2

### ISSUE THREAD

**Issue by kbokdia** [AlexLittlejohn/ALCameraViewController#235]
I am using Xcode 9 with Swift 4
<img width="300" alt="screen shot 2017-10-12 at 2 58 08 pm" src="https://user-images.githubusercontent.com/5452640/31489284-d12d96a6-af5d-11e7-95f6-761c958ac2e0.png">

**Comment by AlexLittlejohn** [comment]
Duplicate of #230
