### ISSUE TITLE
Cropping beyond limits

### ISSUE THREAD

**Issue by RubenKid** [AlexLittlejohn/ALCameraViewController#244]
Cropping functionality allow you to select cropping area beyond image limits making the results not matching the expected behaviour. I believe crop square should be expandable only inside the image frame. Please see attached the cropping process and the result
<img width="311" alt="screen shot 2017-11-15 at 16 26 48" src="https://user-images.githubusercontent.com/1576556/32844238-27a58f1e-ca22-11e7-969f-21411f9c31b1.png">
<img width="240" alt="screen shot 2017-11-15 at 16 28 18" src="https://user-images.githubusercontent.com/1576556/32844239-27d03124-ca22-11e7-9794-1b4f00df02ad.png">

**Comment by luai-kalkatawi** [comment]
+1 @AlexLittlejohn

**Comment by Tulleb** [comment]
It should now be fixed by #254.
Can you please try to reproduce or tell us @RubenKid?

**Comment by RubenKid** [comment]
Hey @Tulleb , just confirmed it works great now!. Thanks a lot!
