### ISSUE TITLE
about IOS Version

### ISSUE THREAD

**Issue by liu1013269528** [AlexLittlejohn/ALCameraViewController#25]
Hi,your demo do a very good job,but not support IOS 7.0,can you fix it ?

**Comment by AlexLittlejohn** [comment]
This component uses the new [````Photos.framework````](https://developer.apple.com/library/ios//documentation/Photos/Reference/Photos_Framework/index.html) from Apple, which was introduced in iOS 8. 
Unfortunately there are no plans to include iOS 7 support.
