### ISSUE TITLE
Camera not working 

### ISSUE THREAD

**Issue by Sopheak0** [AlexLittlejohn/ALCameraViewController#265]
I clone the project and run the app 
  i got this error while using camera 

[Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional]

Class CameraView Line: 42

do {
            input = try AVCaptureDeviceInput(device: device) **** error this line
        } catch let error as NSError {
            input = nil
            print("Error: \(error.localizedDescription)")
            return
 }

**Comment by RoraxHan** [comment]
@Sopheak0  Hello, I met the same problem.
Did you solve this problem?
