### ISSUE TITLE
Spinner is not centred

### ISSUE THREAD

**Issue by evgzor** [AlexLittlejohn/ALCameraViewController#277]
When loading photo is not centrered
![b6ea25ce-7a7e-471b-8ed1-bbdbbdc6eaf4](https://user-images.githubusercontent.com/5227456/45597978-fc33d880-b9dc-11e8-9010-9819224fd244.jpg)

**Comment by Tulleb** [comment]
I think I fixed it in 3.1. Can you check it out again?
