### ISSUE TITLE
imageOrientation

### ISSUE THREAD

**Issue by xcuYao** [AlexLittlejohn/ALCameraViewController#28]
hi , your framework help me a lot.
but how can i judge image is in horizontal  or  vertical take.

**Comment by AlexLittlejohn** [comment]
Assuming you didn't crop the image, you could check if the width is greater than the height which means it is landscape and vice versa

**Comment by xcuYao** [comment]
oh, i am so foolish.
thanks so much.😁

**Comment by AlexLittlejohn** [comment]
👍

**Comment by xcuYao** [comment]
i am sorry trouble you, too.
but i get image.size.whith in horizontal is same in vertical.

**Comment by AlexLittlejohn** [comment]
You can also check the imageOrientation property on UIImage to determine the orientation
