### ISSUE TITLE
hope support xCode10 and Swift4.2

### ISSUE THREAD

**Issue by LuckyRoc** [AlexLittlejohn/ALCameraViewController#284]

**Comment by nadia-am** [comment]
i have this problem ,too. hope it support new version of xcode :(

**Comment by nadia-am** [comment]
i have this problem ,too. hope it support new version of xcode :(

**Comment by Patrick3131** [comment]
I think its just some renames you can change it manually and it should work.

And change NSNotification.Name.UIDevice.orientationDidChangeNotification to UIDevice.orientationDidChangeNotification in
private func addRotateObserver() {
//        NotificationCenter.default.addObserver(
//            self,
//            selector: #selector(rotateCameraView),
//            name: NSNotification.Name.UIDevice.orientationDidChangeNotification,
//            object: nil)
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(rotateCameraView),
            name: UIDevice.orientationDidChangeNotification,
            object: nil)
    }

**Comment by nick-iCars** [comment]
Can you submit a pull request with this change?

**Comment by Tulleb** [comment]
Fixed in 3.1
