### ISSUE TITLE
v3.0.3 Showing ALCameraViewController: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by sabiland** [AlexLittlejohn/ALCameraViewController#285]
I've updated ALCameraViewController to latest 3.0.3 version, but immediately I get error when trying to show it in **iOS Simulator**: **Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value**

```
do {
            input = try AVCaptureDeviceInput(device: device)
        } catch let error as NSError {
            input = nil
            print("Error: \(error.localizedDescription)")
            return
        }
```

**Comment by DavidCollinsNZ** [comment]
This happens when you're using the simulator. It's basically saying that there is no camera available.

**Comment by sabiland** [comment]
Yes, my bad!
