### ISSUE TITLE
XCode Warning : Constraint referencing items turned off ...

### ISSUE THREAD

**Issue by drieran** [AlexLittlejohn/ALCameraViewController#29]
Hi,

Warning: .../Pods/ALCameraViewController/ALCameraViewController/ViewController/ALConfirmViewController.xib: Constraint referencing items turned off in current configuration. Turn off this constraint in the current configuration.

XCode 7.2 (7C68)

Dani

**Comment by AlexLittlejohn** [comment]
This warning refers to nib not having constraints setup in size classes for iPads.

**Comment by drieran** [comment]
Great library! If you can solve this warning I'll appreciate you. Is the unique warning on my project.

**Comment by hellohufan** [comment]
it seems xcode's bug
