### ISSUE TITLE
Component does not work with iOS 9.2 edited photos

### ISSUE THREAD

**Issue by leo-one** [AlexLittlejohn/ALCameraViewController#30]
Thanks for the lib. It is very useful and simple to use (both for developer and users).
I detected that when the user selects a photo that was edited (cropped) in the native "Photos" app in iOS 9.2,  ALCameraViewController shows the photo really very small. It was tested in iPhone 6S Plus.

Regards,

**Comment by AlexLittlejohn** [comment]
This is fixed on the current develop branch and will be merged into master soon™
