### ISSUE TITLE
Compatiblity with iOS 13

### ISSUE THREAD

**Issue by Tulleb** [AlexLittlejohn/ALCameraViewController#301]
Check out #300 if you are looking for a supported fork.

`pod 'ALCameraViewController-Tulleb', '~> 3.1'`

Don't forget to replace `ALCameraViewController` by `ALCameraViewController_Tulleb` in your code also.

**Comment by SreejaG** [comment]
Tried the same in my podfile.
during pod instal, i got the error:
**"Analyzing dependencies
[!] Unable to find a specification for `ALCameraViewController-Tulleb (~> 3.1)`"**

**Comment by Tulleb** [comment]
Fixed in 3.1 version 🎉
