### ISSUE TITLE
Fork with additional features

### ISSUE THREAD

**Issue by kkieffer** [AlexLittlejohn/ALCameraViewController#302]
For anyone interested, I'm maintaining a fork of this repository with additional features, and updated for iOS13 / Swift 5.  Major improvements include variable aspect ratio crop rectangle, layout fixes for portrait/landscape rotation, pinch gesture to show more or less columns in the library picker, and updates to the example.  All original functionality is retained.

See more details here:
https://github.com/kkieffer/ALCameraViewController

**Comment by Tulleb** [comment]
I am closing this since the version 3.1 just got released. Feel free to propose new pull request @kkieffer. I will try to review them with pleasure.
