### ISSUE TITLE
crop scale

### ISSUE THREAD

**Issue by stachon** [AlexLittlejohn/ALCameraViewController#31]
Hello, I love your picker! It is simple and elegant. I have one feature request: to return cropped image in original scale, not current screen size. I made a hack for it in my fork: https://github.com/AlexLittlejohn/ALCameraViewController/compare/master...stachon:master

Regards,
Martin

**Comment by AlexLittlejohn** [comment]
Hi Martin, Thank you for your contribution. I've added this to the develop branch and I will make a release soon™
