### ISSUE TITLE
Segue to cameraViewController is slow

### ISSUE THREAD

**Issue by Fredehagelund92** [AlexLittlejohn/ALCameraViewController#32]
i've implemented the ALCameraViewController, however when a segue is triggered to this it seem to be a bit slow. i've narrowed it down to this line in the ALCameraView `self.session.startRunning()`. Why is that?

**Comment by AlexLittlejohn** [comment]
That line starts up the camera hardware which blocks the thread until its done. It is called off the main thread to mitigate some of this but it is quite an intensive task.

**Comment by yigitserin** [comment]
Can we at least show a  loading dialog on this step ?
