### ISSUE TITLE
Received memory error.

### ISSUE THREAD

**Issue by eeschimosu** [AlexLittlejohn/ALCameraViewController#40]
Usually my app runs with 13Mb to 50Mb of memory. I've used ALCameraViewController attached to a UIButton. When picking a photo from the media library, if the photo is in it's original state (not an optimised one from iCloud), after selecting it and cropping it I receive a memory warning and the app freezes for about 3 seconds. This doesn't happen for an image that is low quality. The use of memory goes to 400Mb - 500Mb. I have no other apps opened when doing this.

This is how I use it. 
```swift
@IBAction func photoAction(sender: AnyObject) {
    let cameraViewController = ALCameraViewController(croppingEnabled: true, allowsLibraryAccess: true) { imageFromController in
      if let wiseImage = imageFromController {
        self.image = wiseImage
      //self.dismissViewControllerAnimated(true, completion: nil)
    }
    self.presentViewController(cameraViewController, animated: false, completion: nil)
  }
```

If I don't dismiss it manually in the block after picking an image from the library, the controller remains opened.

Is it something that maybe I'm doing wrong or something that can be fixed in the library?

**Comment by eeschimosu** [comment]
I've checked and without the cropping  (the same process and image as mentioned previously) it goes up to 94Mb. So it is the cropping that consumes 400Mb more.

**Comment by AlexLittlejohn** [comment]
This is pretty normal when dealing with abnormally large images*. The memory is freed after the cropping is complete. This spike also occurs when selecting large images from the Photo library using the photos framework.

*The photos will be in an uncompressed/RAW format if that is available which can be pretty huge

**Comment by bianjingbulb** [comment]
got  ` Received memory warning.`。　how can i fix it?

**Comment by eeschimosu** [comment]
Can you tell me please where should I add an UIActivityIndicator so the user knows that the camera is loading after clicking done after selecting a image?

**Comment by 917123258** [comment]
When use my iphone6p to take a pic, I got Received memory warning. and then app crashed.　
how can i fix it?

**Comment by 917123258** [comment]
now  I  replaced     UIGraphicsBeginImageContextWithOptions(mutableRect.size, false, 0)  in your ALImageExtensions with  UIGraphicsBeginImageContext(mutableRect.size) .

**Comment by eeschimosu** [comment]
@917123258 Did this fix the Memory Error or made it drop?

**Comment by 917123258** [comment]
@eeschimosu  Now is not a crash, but if the picture is very large, there will be a memory warning

**Comment by AlexLittlejohn** [comment]
I have added a few optimizations for dealing with huge images to the current develop branch which will be release soon™
