### ISSUE TITLE
issues with taking a photo

### ISSUE THREAD

**Issue by stachon** [AlexLittlejohn/ALCameraViewController#41]
Hello, I ran into two issues with photo capture.

1) Sometimes the code to select video connection does not work. I don't know why. Perhaps this is related: http://stackoverflow.com/questions/28336751/inactive-invalid-connection-passed-when-attempting-to-take-a-photo

2) If the user presses the camera button too fast before the camera is ready no image is captured, but then the completion handler is not called and the capture button stays disabled.

This code seems to work for me in ALCameraShot 

```
internal class ALCameraShot: NSObject {
    func takePhoto(stillImageOutput: AVCaptureStillImageOutput, videoOrientation: AVCaptureVideoOrientation, cropSize: CGSize, completion: ALCameraShotCompletion) {
        var videoConnection: AVCaptureConnection? = nil
      
        videoConnection = stillImageOutput.connectionWithMediaType(AVMediaTypeVideo)
        
        videoConnection?.videoOrientation = videoOrientation
        
        stillImageOutput.captureStillImageAsynchronouslyFromConnection(videoConnection!, completionHandler: { buffer, error in
            if buffer != nil {
                let imageData = AVCaptureStillImageOutput.jpegStillImageNSDataRepresentation(buffer)
                let image = UIImage(data: imageData)!
                completion(image)
            } else {
                completion(UIImage())
            }
        })
    }
}
```

**Comment by AlexLittlejohn** [comment]
I've added some checks to counter some of these issues to the current develop branch
