### ISSUE TITLE
Size "vertical" images to fit square crop area

### ISSUE THREAD

**Issue by mad102190** [AlexLittlejohn/ALCameraViewController#42]
In the crop overlay, images with a wide aspect ratio will be stretched (maintaining aspect ratio obviously) to touch the top and bottom of the crop overlay, which is good. However, when using a "tall" image, it is not stretched to fill the crop region, leaving vertical black bars on the sides of the image. Can this be changed to stretch the image until both sides are touching the sides of the crop region? 

![Here's a pic of whats happening with vertical images ](https://cloud.githubusercontent.com/assets/782866/12901839/953862f2-ce72-11e5-9a93-1fa937c3b272.png)

**Comment by AlexLittlejohn** [comment]
Fixed on the current develop branch. Master release soon™
