### ISSUE TITLE
save to camera roll, or maybe just a hint of where image was picked from?

### ISSUE THREAD

**Issue by alexshepard** [AlexLittlejohn/ALCameraViewController#43]
I love how straightforward and easy to use ALCameraViewController is.  :+1: 

Sometimes when my users take photos from within my app, they want their newly saved photos to be saved to the camera roll. Other times (like when they're picking something that's already in the camera roll) they don't want to save to the camera roll.

If this isn't something that ALCameraViewController should do for me, it might be nice just to get a hint of where the image came from in the completion. That way I could decide on my own whether the new image needs saving to the camera roll or not.

Thanks!

**Comment by AlexLittlejohn** [comment]
Saving to the photos library has been added to the current develop branch and will be released soon™

**Comment by alexshepard** [comment]
thanks @AlexLittlejohn!

**Comment by damboscolo** [comment]
How can I do to not save on library?

**Comment by victany5** [comment]
@damboscolo Sorry, there's no way to do that :c

**Comment by suadbay** [comment]
To disable saving the taken photo to camera roll add this: "allowsLibraryAccess: false"

let cameraViewController = CameraViewController(allowsLibraryAccess: false) { [weak self] image, asset in
	// Do something with your image here.
	self?.dismiss(animated: true, completion: nil)
}

present(cameraViewController, animated: true, completion: nil)
