### ISSUE TITLE
can not dismiss ALCameraViewController

### ISSUE THREAD

**Issue by burgesschentz** [AlexLittlejohn/ALCameraViewController#44]
When I click the (X) button, the view controller won't dismiss itself.

**Comment by AlexLittlejohn** [comment]
Im not sure under what circumstances this would occur. Could you provide some more information regarding how you produced this?

**Comment by craigpearce5** [comment]
That just closes the camera.

    presentViewController(cameraViewController, animated: true) { 
            self.dismissViewControllerAnimated(true, completion: nil)
     }

**Comment by AlexLittlejohn** [comment]
This completion block
```swift
let cameraViewController = CameraViewController(croppingEnabled: croppingEnabled) { image in
    self.dismissViewControllerAnimated(true, completion: nil)
}
```
