### ISSUE TITLE
ALCameraViewController can't be initialized

### ISSUE THREAD

**Issue by mrfarukturgut** [AlexLittlejohn/ALCameraViewController#47]
I installed ALCameraViewController by cocoapods and then wanted to try this framework. To do that, In my firstViewController, I imported framework and copied the code snippet below to the viewDidLoad. Although there was no compile errors, I got this runtime warning; 

`2016-02-17 23:22:24.326 App[62509:5556866] Warning: Attempt to present <ALCameraViewController.ALCameraViewController: 0x7bc1e0e0> on <App.FirstViewController: 0x7b919940> whose view is not in the window hierarchy!`

And of course CameraViewController couldn't show up. Can you help?

**Comment by AlexLittlejohn** [comment]
The error in this case is that you've tried to present the camera before your own view controller visible in the stack.

Moving the `presentViewController` line to `viewWillAppear` or `viewDidAppear` should solve this issue

**Comment by mrfarukturgut** [comment]
just worked in `viewDidAppear`. But now there is another error. When the camera sliding up, it throws a run time error and shows up `device.hasFlash` line in the code and prints `unexpectedly found nil while unwrapping an Optional value`. Must I try the camera in the real time machine or what?

**Comment by AlexLittlejohn** [comment]
You will need a real device to test the camera yes

**Comment by MichaelCosmo** [comment]
Hi, I've got the same error : 
`ALCameraViewController.framework> (loaded)' with name 'ConfirmViewController'`  

How can I fix it?

**Comment by mrfarukturgut** [comment]
Yeah, it's still an unanswered question.

**Comment by MichaelCosmo** [comment]
I've just fixed it by coping the file ConfirmViewController.xib into the pod folder of ALCameraViewController. 

Not very good way but it works.

**Comment by AlexLittlejohn** [comment]
I'm in the process of releasing a hotfix for this now. It seems the file names were not updated in the podspec file
