### ISSUE TITLE
Issues with PHAsset

### ISSUE THREAD

**Issue by stachon** [AlexLittlejohn/ALCameraViewController#51]
Hi Alex, excellent work with PHAssets! Cropping is now much faster. Though, there are a few issues:

* Cropping is broken. It seems that the `normalizedCropRect` depends on image orientation. This code works for me in ConfirmViewController: 

```Swift
internal func confirmPhoto() {
        
        let fetcher = SingleImageFetcher()
            .onSuccess { image in
                self.onComplete?(image)
            }
            .onFailure { error in
            
            }
            .setAsset(asset)
        
        if allowsCropping {
            
            var cropRect = cropOverlay.frame
            cropRect.origin.x += scrollView.contentOffset.x
            cropRect.origin.y += scrollView.contentOffset.y
            
            let normalizedX = cropRect.origin.x / imageView.frame.width
            let normalizedY = cropRect.origin.y / imageView.frame.height
            
            let normalizedWidth = cropRect.width / imageView.frame.width
            let normalizedHeight = cropRect.height / imageView.frame.height
            
            var normalizedRect: CGRect!
          
            // the rectangle depends on photo orientation
            switch imageView.image!.imageOrientation {
            case .Up:
              normalizedRect = CGRect(x: normalizedX, y: normalizedY, width: normalizedWidth, height: normalizedHeight)
            case .Down:
              normalizedRect = CGRect(x: 1-normalizedX-normalizedWidth, y: 1-normalizedY-normalizedHeight, width: normalizedWidth, height: normalizedHeight)
            case .Left:
              normalizedRect = CGRect(x: 1-normalizedY-normalizedHeight, y: normalizedX, width: normalizedHeight, height: normalizedWidth)
            case .Right:
              normalizedRect = CGRect(x: normalizedY, y: 1-normalizedX-normalizedWidth, width: normalizedHeight, height: normalizedWidth)
            default:
              normalizedRect = CGRect(x: normalizedX, y: normalizedY, width: normalizedWidth, height: normalizedHeight)
            }
            
            fetcher.setCropRect(normalizedRect)
        }
        
        fetcher.fetch()
    }
```

* Cropping with zoom yields very low resolution images. You calculate the targetSize this way in SingleImageFetcher:fetch() :

```Swift
let targetWidth = floor(CGFloat(asset.pixelWidth) * cropRect.width)
let targetHeight = floor(CGFloat(asset.pixelHeight) * cropRect.height)
```

But it looks like asset.pixelWidth does not return the original full size of image, but rather size on screen. I made a workaround for now, don't know the correct solution yet ::

```Swift
targetSize = CGSize(width: 1024, height: 1024)
```

* When choosing from Library, images stored in iCloud do not work. Didn't look into that one yet.

Thank you,
MS

**Comment by AlexLittlejohn** [comment]
Ive added network access for images, which allows them to be fetched from iCloud if necessary. Currently on develop

**Comment by AlexLittlejohn** [comment]
Im not seeing the issue with crop rotation when I take photos sideways or upside down on neither the front nor the rear camera? I am however seeing that it offsets the crop rect & zoom slightly when it crops

**Comment by AlexLittlejohn** [comment]
There is an open rdar about the pixel size of the images http://www.openradar.me/21045111

**Comment by stachon** [comment]
I tested it on IPhone 5S back camera. Just zoom in a rect away from the center of the image. Cropping was only correct when I took the photo in landscape mode with Home button on the right. Now tested also with front camera, the code I posted is not correct for Front camera.

**Comment by AlexLittlejohn** [comment]
Adding the extra case statements seems to fix it for the front camera aswell

**Comment by AlexLittlejohn** [comment]
Ive added fixes for these issues to the develop branch and a workaround for the crop image size.
Thank you for your help with these.

**Comment by stachon** [comment]
Thank you!

**Comment by jonysingla** [comment]
Hi Alex, whenever I select pic from gallery , the size of the picture is small. When I crop this image its stretch too large size image. Can you please let me know what is the reason for this.
