### ISSUE TITLE
Color of image swapped using WebP framework

### ISSUE THREAD

**Issue by tecexpert** [AlexLittlejohn/ALCameraViewController#52]
I have been trying to convert image to WebP format after user captures/selects the image using WebP framework.
The issue is the color of the images get swapped after using your library.

Original Image:

![4dd9781ead43cde49d4717f8b718c14ff20fb15c6f4e3188b7pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17078055/13217183/a2f74506-d986-11e5-8fd2-df637f3545e1.jpg)

Image after converting to WebP format:

![1ad35e34b7a8854295bb9f54636c5e979ae65e8a74f1ba0723pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17078055/13217194/af478942-d986-11e5-87ed-b7020d6d849e.jpg)

The library source is: https://github.com/seanooi/iOS-WebP

Note : I have tried it with Simple image and default iOS image picker, the images were converting to WebP correctly.

**Comment by AlexLittlejohn** [comment]
It is strange that this is happening, however the library doesn't do any color conversions on the images at all - it only uses the `Photos.framework` methods for fetching the images from the photo library and cropping.

I might suggest looking at the values provided to the WebP convertor you are using in this case i.e.
https://github.com/seanooi/iOS-WebP#config-block as other users have also mentioned shifting colors when converting images, perhaps this is of use? https://github.com/seanooi/iOS-WebP/issues/27, https://github.com/seanooi/iOS-WebP/issues/10

**Comment by tecexpert** [comment]
Thanks for such a quick response!!!

The issue is resolved using https://github.com/seanooi/iOS-WebP/issues/27 lostkid's solution!

But I still wonder why would I need this solution , if WebP framework is working fine without AL Library?

[WebPImage-Static-Default-AL.zip](https://github.com/AlexLittlejohn/ALCameraViewController/files/140556/WebPImage-Static-Default-AL.zip)
