### ISSUE TITLE
Question - regarding image size

### ISSUE THREAD

**Issue by tiviti** [AlexLittlejohn/ALCameraViewController#57]
Is there a way to set  the  cropping dimensions?

For example, we want image to be 130 x 600.

**Comment by AlexLittlejohn** [comment]
Duplicate: #15 
This is not yet available in the library yet. 
If you need it desperately I can suggest this library [TOCropViewController](https://github.com/TimOliver/TOCropViewController) in the meantime.

**Comment by tiviti** [comment]
Thanks for the reference 

Ilan
