### ISSUE TITLE
Allow using ALCameraViewController separately

### ISSUE THREAD

**Issue by qizh** [AlexLittlejohn/ALCameraViewController#63]
I'm using this controller in my project for making and then cropping photo, but I use default image picker for picking photos. I would love to use your cropping functionality with an image user picked with other picker. On version `1.1.3` I was doing it like this:

		let croppingController = ALCameraViewController.croppingViewController(image, croppingEnabled: true) { image in
			self.useImage(image)
		}
		picker.presentViewController(croppingController, animated: true, completion: nil)

Can you let me do something similar in newer versions and keep it as public API?

**Comment by AlexLittlejohn** [comment]
This is resolved in the next release :)

**Comment by strawberrycode** [comment]
+1 for the "cropping only" functionality
Just checking on its status since you released 1.1.9 recently ;)
Thanks
