### ISSUE TITLE
cannot get module to load

### ISSUE THREAD

**Issue by JordanRoPo** [AlexLittlejohn/ALCameraViewController#7]
I keep getting this error: "Cannot load underlying module for 'ALCameraViewController" when i try to import the ALCameraViewController module and "Use of unresolved identifier 'ALCameraViewController'" for when i remove it? I haven't had a problem when installing the pod either ....any suggestions? 

Anybody have any reason why using cocoapods won't work?

**Comment by AlexLittlejohn** [comment]
I've had this issue with Cocoapods occasionally. To fix it you just need to build the project once. As far as i know this has been fixed with the latest Cocoapods release

**Comment by bianjingbulb** [comment]
I also had this issue and could't fix it by building the project once again

**Comment by bianjingbulb** [comment]
Just solved this issue by adding `import ALCameraViewController` to the head of the viewController file.
