### ISSUE TITLE
Zooming doesn't work on the camera

### ISSUE THREAD

**Issue by mbalex99** [AlexLittlejohn/ALCameraViewController#70]
Zooming doesn't work on the camera.

**Comment by ppamorim** [comment]
Which type of zoom you prefer, while the use of the camera or in the crop process? Or both?

**Comment by mbalex99** [comment]
While use of the camera. I think the crop isn't necessary at the moment.
On Sat, Apr 2, 2016 at 12:04 PM Pedro Paulo Amorim <notifications@github.com>
wrote:

> Which type of zoom you prefer, while the use of the camera or in the crop
> process? Or both?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AlexLittlejohn/ALCameraViewController/issues/70#issuecomment-204783137>
>
-- 
Maximilian Alexander
mbalex99@gmail.com
http://blog.edenmsg.com

**Comment by Cyclic** [comment]
Has someone implemented this feature/enhancement, and if not, will this work for us?
`let minimumZoom: CGFloat = 1.0
let maximumZoom: CGFloat = 3.0
var lastZoomFactor: CGFloat = 1.0

func pinch(_ pinch: UIPinchGestureRecognizer) {
    guard let device = videoDeviceInput.device else { return }

    // Return zoom value between the minimum and maximum zoom values
    func minMaxZoom(_ factor: CGFloat) -> CGFloat {
        return min(min(max(factor, minimumZoom), maximumZoom), device.activeFormat.videoMaxZoomFactor)
    }

    func update(scale factor: CGFloat) {
        do {
            try device.lockForConfiguration()
            defer { device.unlockForConfiguration() }
            device.videoZoomFactor = factor
        } catch {
            print("\(error.localizedDescription)")
        }
    }

    let newScaleFactor = minMaxZoom(pinch.scale * lastZoomFactor)

    switch pinch.state {
    case .began: fallthrough
    case .changed: update(scale: newScaleFactor)
    case .ended:
        lastZoomFactor = minMaxZoom(newScaleFactor)
        update(scale: lastZoomFactor)
    default: break
    }
}`

Grabbed it from here:
https://stackoverflow.com/questions/33180564/pinch-to-zoom-camera
