### ISSUE TITLE
Option to not save photo in image library

### ISSUE THREAD

**Issue by ankitgoyal100** [AlexLittlejohn/ALCameraViewController#73]
Can you implement an option to not save the photo in the device's image library?

**Comment by AlexLittlejohn** [comment]
The tight integration with the photos framework makes this almost impossible. The framework handles the cropping and resizing of photos as well as ensuring that the apps memory usage is kept low by allowing us to use lower quality representations of images for display.

**Comment by MarcelStructr** [comment]
I also don't want the Image to be saved into the device's image library. 
Do you have any workaround for this? Besides that your amazing work fits perfectly in my Application.

**Comment by ppamorim** [comment]
Workarounds are not allowed here. Cheers...

**Comment by AlexLittlejohn** [comment]
No updates for a while. Closing this issue.
