### ISSUE TITLE
How to change image orientation when UI is locked in portrait?

### ISSUE THREAD

**Issue by robski05** [AlexLittlejohn/ALCameraViewController#78]
When I take a cropped photo in landscape with UI locked, the photo is in wrong orientation in preview. How can I change the orientation?

**Comment by ppamorim** [comment]
Please check #80

**Comment by majid701** [comment]
@AlexLittlejohn @ppamorim 
Guys any update on this? As per now putting the device in landscape mode causes the capture button to move the bottom center of the screen thats correct but its much easier for the user to take the picture if the controls stay as they are on portrait mode but the image which comes out is rotated! Any way to achieve this?
