### ISSUE TITLE
Cropped image in original resolution

### ISSUE THREAD

**Issue by madelman** [AlexLittlejohn/ALCameraViewController#8]
When doing the photos in normal mode, the image returned has a size of 3264 x 2448 pixels. But when using the option to crop the image to a square, it always return a size of 690 x 690 pixels.

Is there any way to get a square image but with the original resolution?

**Comment by AlexLittlejohn** [comment]
I've made changes to fix this which are on the current develop branch

**Comment by licvido** [comment]
Hi, it still returns weird scaled images in version ``1.1.2``.
``1152x1152`` on iPhone 6 Plus, ``690x690`` on iPhone 6, ``580x580`` on iPhone 5, etc.

**Comment by tecexpert** [comment]
I am having the same issue 580x580 size in 5s.
