### ISSUE TITLE
AutoLayout conflict

### ISSUE THREAD

**Issue by ppamorim** [AlexLittlejohn/ALCameraViewController#81]
Please remove this line:

https://github.com/AlexLittlejohn/ALCameraViewController/blob/master/ALCameraViewController/ViewController/CameraViewController.swift#L294-L299

This can cause a layout conflict because the first two parameters do this, we don't need it

EDIT:

It doesn't make any sense, you cannot use these values of the screen to determinate where is the center of the view. We need to use a pure implementation of AutoLayout to do this.

EDIT2:

AutoLayout is VERY sensitive, be alert with any constraint conflict otherwise it will crash(break another constraints).

**Comment by AlexLittlejohn** [comment]
In hindsight i realise that its not providing any value, however it isn't breaking anything at the moment. I will remove it anyway.

**Comment by AlexLittlejohn** [comment]
> It doesn't make any sense, you cannot use these values of the screen to determinate where is the center of the view. We need to use a pure implementation of AutoLayout to do this.

Are you referring to the next constraint which vertically centers the overlay between the buttons?

**Comment by ppamorim** [comment]
@AlexLittlejohn I don't recognize any problem with overlapping of views with this approach, I'm testing on a iPhone 4S and it works very good.
