### ISSUE TITLE
the x button removes the image

### ISSUE THREAD

**Issue by andreiurzica** [AlexLittlejohn/ALCameraViewController#84]
hello there
i have a problem 
if i select a photo from gallery and hit the check/ok/apply everything is ok, the selected image updates the   UIImage 
But if i enter the gallery and i hit the top left x, the image from UIImage dissapears
Same thing with camera.
Waiting for an answer.

**Comment by AlexLittlejohn** [comment]
If you're referring to the example app then yes, thats the way its supposed to work i.e. If you select an image  you'll see an image otherwise you'll see nothing.

**Comment by andreiurzica** [comment]
i'm not talking about the example...
i use this in my app

```
        let libraryViewController = ALCameraViewController.imagePickerViewController(true) { image, asset in
            self.poza_profil.image = image
            self.dismissViewControllerAnimated(true, completion: nil)
        }
        
        presentViewController(libraryViewController, animated: true, completion: nil)
```

**Comment by AlexLittlejohn** [comment]
If you set a UIImageView's image to nil it will clear its image. The library returns nil if you don't choose or take an image

**Comment by andreiurzica** [comment]
can you modify that?
the user enters the profile edit
click on image change 
and after that he reconsiders and hits x
and the old image should stay there
now when is hits x as you said the uiimage is set to nil 
and the user thinks that the picture was deteled

i hope u got the point

**Comment by andreiurzica** [comment]
if you dont choose or take picture the old UIImage shouldn't be deleted

**Comment by AlexLittlejohn** [comment]
The library isn't deleting your image at all, just add a check to your code to see if an image is returned otherwise don't do anything. eg.
```swift
let libraryViewController = ALCameraViewController.imagePickerViewController(true) { image, asset in
  if let image = image { // Add a check to prevent you from clearing your image...
    self.poza_profil.image = image
  }
  self.dismissViewControllerAnimated(true, completion: nil)
}
```
