### ISSUE TITLE
Edited Image

### ISSUE THREAD

**Issue by gunyduny** [AlexLittlejohn/ALCameraViewController#88]
I have been playing around with the ConfirmViewController by adding some image filter selections to this file.  The problem that I am running into is the variable for the final image. For example if i change this the code in confirmPhoto()

`.onSuccess { image in
                self.onComplete?(image, self.asset)`

to this

`.onSuccess { image in
                self.onComplete?(imageView.image, self.asset)`

The filter saves but not the cropped image but will save the image when cropping is not enabled.  Where in this file do I apply the filter for the cropped image.
If you like I can include the edited file. when asked.

**Comment by AlexLittlejohn** [comment]
In `confirmPhoto` the actual size image is retrieved from the photo library. Up to this point we've only been working with a low res placeholder image. With this in mind you'll want to do add any filters to the final image after this point.

**Comment by gunyduny** [comment]
Thanks, which is the final image variable or function.

**Comment by gunyduny** [comment]
Ok after much analyzing, i created this, but I always receive the permission to modify image, I see that you do it whith out the popup when you crop the image.  What am I am missing.

`asset.requestContentEditingInputWithOptions(nil) { (contentEditingInput: PHContentEditingInput?, _) -> Void in
                //Get full image
                let url = contentEditingInput!.fullSizeImageURL
                let orientation = contentEditingInput!.fullSizeImageOrientation
                var inputImage = CIImage(contentsOfURL: url!)
                inputImage = inputImage!.imageByApplyingOrientation(orientation)
                let editedImageData = UIImageJPEGRepresentation(self.imageView.image!, 1.0)//This is my altered image that is displayed in the Confirm View
                let output = PHContentEditingOutput(contentEditingInput: contentEditingInput!)
                editedImageData!.writeToURL(output.renderedContentURL,
                                           atomically: true)
                output.adjustmentData =
                    PHAdjustmentData(formatIdentifier: "com.zero.ALCameraViewController.LibraryQueue",
                                     formatVersion: "0.1",
                                     data: CIfilterName.dataUsingEncoding(NSUTF8StringEncoding,
                                        allowLossyConversion: false)!)
                
                PHPhotoLibrary.sharedPhotoLibrary().performChanges({ () -> Void in
                    let request = PHAssetChangeRequest(forAsset: self.asset)
                    request.contentEditingOutput = output
                    }, completionHandler: { (success, error) -> Void in
                        if success == false { print("failed to commit image edit: \(error)") } //fails unless metadata is replaced with nil above
                })
            }
`

**Comment by AlexLittlejohn** [comment]
No updates for a while. Closing this issue.
