### ISSUE TITLE
Received memory warning.

### ISSUE THREAD

**Issue by fatihyildizhan** [AlexLittlejohn/ALCameraViewController#9]
1- I was running the original code on iPhone 6 Plus. I've done few things then the app crashed when I clicked the Camera.
2- It can be related to "whose view is not in the view hierarchy!"

![memory warning](https://cloud.githubusercontent.com/assets/602600/10794612/56bd6bc8-7d9e-11e5-98aa-57e83e70f5f0.png)

**Comment by AlexLittlejohn** [comment]
Im going to need more information than this in order to reproduce this issue. 
i.e. the exact steps taken and how many other apps were running at the time etc

**Comment by dpakthakur** [comment]
Even I am facing this issue. App crashes in iPhone 6s+ if I tap on 'tick' button in captured camera image.
