### ISSUE TITLE
Sintax error with ALCameraViewController in Swift2

### ISSUE THREAD

**Issue by kike0kike** [AlexLittlejohn/ALCameraViewController#90]
I have a sintax error trying to include the pod "ALCameraViewController" of AlexLittlejohn in my project. All the sintax errors are like "Expected ',' separator". The errors are in the library...

![error](https://cloud.githubusercontent.com/assets/4818973/14630202/58a827ec-060c-11e6-9be8-cd9dce449efb.png)

Thanks!

**Comment by AlexLittlejohn** [comment]
You need to upgrade your Xcode to the latest version in order to run the example app.
