### ISSUE TITLE
Use only the cropper(not the camera)

### ISSUE THREAD

**Issue by happiehappie** [AlexLittlejohn/ALCameraViewController#93]
Just wondering if this is possible

**Comment by AlexLittlejohn** [comment]
It is possible, however is uses `PHAssets` instead of images to do the work

**Comment by happiehappie** [comment]
How do I call the cropper without presenting the camera view??

On Thursday, 21 April 2016, Alex Littlejohn <notifications@github.com>
wrote:

> It is possible, however is uses PHAssets instead of images to do the work
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AlexLittlejohn/ALCameraViewController/issues/93#issuecomment-212785807>
>


-- 
Best Regards,
Stanley

**Comment by AlexLittlejohn** [comment]
Something like this

```swift
let confirmViewController = ConfirmViewController(asset: **PHAsset**, allowsCropping: true)
confirmViewController.onComplete = { image, asset in 
    // do something with your cropped image here
}
```

**Comment by happiehappie** [comment]
How do I make my image to PHAsset? Must I save them first?

**Comment by happiehappie** [comment]
Also am I able to like.. change the button colors etc?

**Comment by happiehappie** [comment]
Cause I get unresolved identifier of ConfirmViewController even if I imported ALCameraViewController
