### ISSUE TITLE
Error on update to 1.1.9

### ISSUE THREAD

**Issue by leo-one** [AlexLittlejohn/ALCameraViewController#96]
I am currently using the 1.1.2 version. When I update to 1.1.9, the error below is shown:
"Cannot call value of non-function type 'module< ALCameraViewController >'"

It points to line that calls the method ALCameraViewController(croppingEnabled: true) { }.

If I downgrade to 1.1.2, it works as expected.

**Comment by AlexLittlejohn** [comment]
Change `ALCameraViewController`to `CameraViewController`
