### ISSUE TITLE
Install the library manullay  

### ISSUE THREAD

**Issue by subhashisrouth** [AlexLittlejohn/ALCameraViewController#98]
Hi,
How to include this library manually without using CocoaPods. Please help me, as soon as possible.

**Comment by AlexLittlejohn** [comment]
Download the project and Add everything from the classes folder to your
project directly. Then instantiate as shown in the example.

**Comment by subhashisrouth** [comment]
Yes, its working if I put all files directly at root of my project, however after open the camera, I could not close the camera.

**Comment by AlexLittlejohn** [comment]
Ah, you will also need the confirmview
controller .xib, cameraview.strings and Cameraviewassets.xcassets files

**Comment by subhashisrouth** [comment]
Yes, I have added them also.

**Comment by subhashisrouth** [comment]
This is great library for iOS app and works fine, however I failed to install it in my cordova project correctly, so instead I use cordova-plugin-crop which gives both support for android and cordova.
