### ISSUE TITLE
Previous screens flash briefly

### ISSUE THREAD

**Issue by stevejcox** [AlexLittlejohn/ALCameraViewController#99]
I seem to be coming across an issue where other screens briefly flash before the camera view controller can be dismissed.

To replicate simply open up the camera, choose the library button, select an image then click the tick. 

I'm looking to narrow down the problem code now, but if you have any clues that would be great!

**Comment by stevejcox** [comment]
Looked into this a touch. Issue seems to be that the confirm view controller is getting dismissed, showing the camera view controller for a split second before that is dismissed. 

Any suggestions on how I could tweak to make both dismiss at the same time? Seems to just be code execution time that's causing the problem.

**Comment by pavan309** [comment]
Raised a [PR](https://github.com/AlexLittlejohn/ALCameraViewController/pull/133) for this issue.

**Comment by AlexLittlejohn** [comment]
Fixed on develop, release soon
